### ISSUE TITLE
`Calling getSourceAs when a newer style is loading/has loaded.` exception

### ISSUE THREAD

**Issue by torrybr** [ramani-maps/ramani-maps#110]
An exception when clicking ""Center on device location" on user location & having `cameraMode` set. Unsure if this is tied to the new style refactor introduced in `v0.8.0`

**Reproducible snippet using [Location Example](https://github.com/ramani-maps/ramani-maps/blob/main/examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt)

```
      Box {
                    Surface(
                        modifier = Modifier.fillMaxSize(),
                        color = MaterialTheme.colorScheme.background
                    ) {
                        MapLibre(
                            modifier = Modifier.fillMaxSize(),
                            styleBuilder = Style.Builder()
                                .fromUri(resources.getString(R.string.maplibre_style_url)),
                            cameraPosition = cameraPosition.value,
                            locationRequestProperties = locationProperties.value,
                            locationStyling = LocationStyling(
                                enablePulse = true,
                                pulseColor = Color.YELLOW,
                            ),
                            renderMode = RenderMode.COMPASS,
                            userLocation = userLocation,
                            cameraMode = CameraMode.TRACKING,
                        )
                    }
                    Button(
                        modifier = Modifier.align(Alignment.BottomCenter),
                        onClick = {
                            cameraPosition.value = CameraPosition(cameraPosition.value).apply {
                                this.target = LatLng(
                                    userLocation.value.latitude,
                                    userLocation.value.longitude
                                )
                            }
                        },
                    ) {
                        Text(text = "Center on device location")
                    }
                }
```

**Error**

```
024-12-06 17:32:46.895  7802-7802  AndroidRuntime          org.ramani.example.location          E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: org.ramani.example.location, PID: 7802
                                                                                                    java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.
                                                                                                    	at org.maplibre.android.maps.Style.validateState(Style.java:776)
                                                                                                    	at org.maplibre.android.maps.Style.getSourceAs(Style.java:147)
                                                                                                    	at org.maplibre.android.location.SymbolLocationLayerRenderer.refreshSource(SymbolLocationLayerRenderer.java:322)
                                                                                                    	at org.maplibre.android.location.SymbolLocationLayerRenderer.setBearingProperty(SymbolLocationLayerRenderer.java:338)
                                                                                                    	at org.maplibre.android.location.SymbolLocationLayerRenderer.setCompassBearing(SymbolLocationLayerRenderer.java:173)
                                                                                                    	at org.maplibre.android.location.LocationLayerController$3.onNewAnimationValue(LocationLayerController.java:281)
                                                                                                    	at org.maplibre.android.location.LocationLayerController$3.onNewAnimationValue(LocationLayerController.java:278)
                                                                                                    	at org.maplibre.android.location.MapLibreAnimator.postUpdates(MapLibreAnimator.java:106)
                                                                                                    	at org.maplibre.android.location.MapLibreAnimator.onAnimationUpdate(MapLibreAnimator.java:93)
                                                                                                    	at android.animation.Animator$AnimatorCaller.lambda$static$4(Animator.java:858)
                                                                                                    	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda6.call(Unknown Source:4)
                                                                                                    	at android.animation.Animator.callOnList(Animator.java:669)
                                                                                                    	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1645)
                                                                                                    	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:771)
                                                                                                    	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:734)
                                                                                                    	at android.animation.ValueAnimator.start(ValueAnimator.java:1154)
                                                                                                    	at android.animation.ValueAnimator.start(ValueAnimator.java:1173)
                                                                                                    	at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1166)
                                                                                                    	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1293)
                                                                                                    	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1364)
                                                                                                    	at android.animation.AnimatorSet.start(AnimatorSet.java:745)
                                                                                                    	at android.animation.AnimatorSet.start(AnimatorSet.java:696)
                                                                                                    	at org.maplibre.android.location.MapLibreAnimatorSetProvider.startAnimation(MapLibreAnimatorSetProvider.java:31)
                                                                                                    	at org.maplibre.android.location.LocationAnimatorCoordinator.playAnimators(LocationAnimatorCoordinator.java:396)
                                                                                                    	at org.maplibre.android.location.LocationAnimatorCoordinator.resetAllLayerAnimations(LocationAnimatorCoordinator.java:490)
                                                                                                    	at org.maplibre.android.location.LocationComponent.updateAnimatorListenerHolders(LocationComponent.java:1387)
                                                                                                    	at org.maplibre.android.location.LocationComponent.-$$Nest$mupdateAnimatorListenerHolders(Unknown Source:0)
                                                                                                    	at org.maplibre.android.location.LocationComponent$8.onCameraTrackingChanged(LocationComponent.java:1525)
                                                                                                    	at org.maplibre.android.location.LocationCameraController.notifyCameraTrackingChangeListener(LocationCameraController.java:354)
                                                                                                    	at org.maplibre.android.location.LocationCameraController.setCameraMode(LocationCameraController.java:125)
                                                                                                    	at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:387)
                                                                                                    	at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:351)
                                                                                                    	at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:326)
                                                                                                    	at org.maplibre.android.location.LocationComponent$10.onDeveloperAnimationStarted(LocationComponent.java:1550)
                                                                                                    	at org.maplibre.android.maps.MapLibreMap.notifyDeveloperAnimationListeners(MapLibreMap.java:2524)
                                                                                                    	at org.maplibre.android.maps.MapLibreMap.animateCamera(MapLibreMap.java:734)
                                                                                                    	at org.maplibre.android.maps.MapLibreMap.animateCamera(MapLibreMap.java:708)
                                                                                                    	at org.ramani.compose.MapLibreKt.MapUpdater$lambda$57$lambda$56(MapLibre.kt:460)
                                                                                                    	at org.ramani.compose.MapLibreKt.$r8$lambda$4GPs-4M9S4zFhOvug2rIOzMnMk0(Unknown Source:0)
                                                                                                    	at org.ramani.compose.MapLibreKt$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.runtime.changelist.Operation$UpdateNode.execute(Operation.kt:451)
2024-12-06 17:32:46.896  7802-7802  AndroidRuntime          org.ramani.example.location          E  	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:310) (Ask Gemini)
                                                                                                    	at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:81)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1013)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:685)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:878)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@a185885, androidx.compose.ui.platform.MotionDurationScaleImpl@33466da, StandaloneCoroutine{Cancelling}@b42670b, AndroidUiDispatcher@42d69e8]
2024-12-06 17:32:46.901   565-7874  DropBoxManagerService   pid-565                              I  add tag=data_app_crash isTagEnabled=true flags=0x2
```

**Comment by JonasVautherin** [comment]
Would you mind trying [this PR](https://github.com/ramani-maps/ramani-maps/pull/112) and letting me know if it helps?

**Comment by ginnyTheCat** [comment]
I'm still getting this exception even using the `0.8.2` version, when moving the map while the `cameraMode` is set to `TRACKING`

**Comment by JonasVautherin** [comment]
Do you have a reproducible example or does it happen randomly?

**Comment by JonasVautherin** [comment]
I think it should be better with 0.11.0 (note that the API changed a bit). Let me know if it makes a difference!
