### ISSUE TITLE
java.lang.Error: Cannot remove detached source

### ISSUE THREAD

**Issue by klemensz** [ramani-maps/ramani-maps#118]
With a recent update (main branch) I get this error when loading the map:

```
java.lang.Error: Cannot remove detached source
                 	at org.maplibre.android.maps.NativeMapView.nativeRemoveSource(Native Method)
                 	at org.maplibre.android.maps.NativeMapView.removeSource(NativeMapView.java:962)
                 	at org.maplibre.android.maps.Style.removeSource(Style.java:176)
                 	at org.ramani.compose.MapLibreKt$MapLibre$6$1.invokeSuspend(MapLibre.kt:147)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:68)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1687)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
                 	at android.view.Choreographer.doFrame(Choreographer.java:1069)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:230)
                 	at android.os.Looper.loop(Looper.java:319)
                 	at android.app.ActivityThread.main(ActivityThread.java:8919)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@b9557cd, androidx.compose.runtime.BroadcastFrameClock@4e50882, StandaloneCoroutine{Cancelling}@4a86b93, AndroidUiDispatcher@32ec7d0]
```

I initially pass empty lists as sources and styles, and modify those in the `onStyleLoaded` callback. Maybe it's related to this?

**Comment by JonasVautherin** [comment]
Instead of manipulating the Style directly, does it work if you modify `sources` and `layers` [here](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L111-L112)?

**Comment by klemensz** [comment]
That's actually what I do. 🤔 RamaniMaps is just a wrapper for MapLibre.

```kt
                    val mapSources by sources.collectAsState(emptyList())
                    val mapLayers by layers.collectAsState(emptyList())
                    val mapLibreMapView = rememberMapViewWithLifecycle()
                    mapLibreMapView.getMapAsync { map ->
                        locationComponent = map.locationComponent
                    }
                    RamaniMaps(
                        modifier = Modifier.padding(bottom = 24.dp),
                        onMapClick = rememberLambda { point ->
                            onMapClick(point)
                        },
                        mapView = mapLibreMapView,
                        onStyleLoaded = rememberLambda { style ->
                            // sources and layers value is set here
                        },
                        sources = mapSources,
                        layers = mapLayers,
                    )
```

**Comment by JonasVautherin** [comment]
And when do you say it crashes? Directly when you modify them in `onStyleLoaded`?

It is crashing [here](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L147). Is it correct that you don't set a `StyleBuilder`? I think there is an issue with the default one. Can you try creating a style builder e.g. at the top of the code snippet, and pass it to `RamaniMaps`?

I need to change something regarding the `LaunchedEffect` and the `StyleBuilder`, because depending on how it's passed it will always recompose (the equality check doesn't work).

**Comment by miikahameenaho** [comment]
I stumbled recently into same issue, have not figured out is there currently any way to utilize sources and layers as whatever I have tried ends up to this same crash. 🤔

**Comment by JonasVautherin** [comment]
Would you be able to provide a reproducible example?

**Comment by Vanosuperhero** [comment]
Hi! I ran into the same error when trying to change the camera position. However, the error doesn’t occur if I have no layers in the layers parameter or if styleBuilder = Style.Builder() (which results in a black screen).

**Comment by JonasVautherin** [comment]
I refactored the API a bit in v0.11.0 and took the opportunity to fix a bunch of bugs. This may be better now, let me know!

**Comment by klemensz** [comment]
I don't use the library any more currently so I cannot really verify it, but I hope someone else can :)
