### ISSUE TITLE
drawable/maplibre_user_icon_shadow has unresolved theme attributes

### ISSUE THREAD

**Issue by superBleep** [ramani-maps/ramani-maps#66]
Runtime exception thrown when adding user location blip on map, crashes the VM I'm using.
```
java.lang.RuntimeException
at android.content.res.Resources.getDrawable(Resources.java:908)
at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:183)
at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:169)
at com.mapbox.mapboxsdk.location.LayerBitmapProvider.generateShadowBitmap(LayerBitmapProvider.java:30)
at com.mapbox.mapboxsdk.location.LocationLayerController.styleBitmaps(LocationLayerController.java:162)
at com.mapbox.mapboxsdk.location.LocationLayerController.applyStyle(LocationLayerController.java:98)
at com.mapbox.mapboxsdk.location.LocationLayerController.initializeComponents(LocationLayerController.java:79)
at com.mapbox.mapboxsdk.location.LocationLayerController.<init>(LocationLayerController.java:72)
at com.mapbox.mapboxsdk.location.LocationComponent.initialize(LocationComponent.java:1092)
at com.mapbox.mapboxsdk.location.LocationComponent.activateLocationComponent(LocationComponent.java:250)
```
The code that triggers it:
```
MapLibre(
    styleUrl = "https://demotiles.maplibre.org/styles/osm-bright-gl-style/style.json",
    modifier = Modifier.fillMaxSize(),
    cameraPosition = cameraPosition,
    locationRequestProperties = LocationRequestProperties(
        interval = LOCATION_UPDATE_FREQ
    ),
    userLocation = userLocation
)
```
Seems to be similar to [this](https://github.com/maplibre/maplibre-native/issues/1274) issue on the main maplibre-native repo.

Using `implementation("org.ramani-maps:ramani-maplibre:0.3.0")`
VM: Pixel 7 API 33

**Comment by JonasVautherin** [comment]
Did you try updating the maplibre transitive dependency? Maybe that just does it?

**Comment by superBleep** [comment]
I’ve tried updating the dependency, but the fix is included in a prerelease that has changed some things in the library since the `10.2.0` release you’re using.

Most importantly, the package has been renamed from `com.mapbox.mapboxsdk` to `org.maplibre.android`, as detailed [here](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre0).

**Comment by JonasVautherin** [comment]
Got it, I'll try to update it ASAP. In the meantime, feel free to open a PR if you get to it first!
